package pyde

// Codec-parity conformance: proves the Go borsh Encoder/Decoder are byte-
// identical to Rust `borsh::to_vec`, with no mock and no fabricated bytes.
// Reads the SAME golden vectors the AssemblyScript SDK uses
// (vectors/codec_borsh.json, generated by rust/pyde-host/tests/
// codec_borsh_goldens.rs). For every vector:
//
//	ENCODE   — build the value from the golden `input`, encode, and assert the
//	           bytes equal the golden `borsh`.
//	REENCODE — decode the golden `borsh` bytes and re-encode, asserting the
//	           round-trip reproduces `borsh` and consumes every byte.
//
// This test is native-only (uses U128FromString etc. from the !tinygo file).

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"strconv"
	"testing"
)

type borshVector struct {
	Name  string          `json:"name"`
	Type  string          `json:"type"`
	Input json.RawMessage `json:"input"`
	Borsh string          `json:"borsh"`
}

func loadBorshGoldens(t *testing.T) []borshVector {
	t.Helper()
	raw, err := os.ReadFile("../vectors/codec_borsh.json")
	if err != nil {
		t.Fatalf("read goldens: %v", err)
	}
	var doc struct {
		Vectors []borshVector `json:"vectors"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse goldens: %v", err)
	}
	if len(doc.Vectors) == 0 {
		t.Fatal("no golden vectors")
	}
	return doc.Vectors
}

func jsonStr(t *testing.T, raw json.RawMessage) string {
	t.Helper()
	var s string
	if err := json.Unmarshal(raw, &s); err != nil {
		t.Fatalf("input not a string: %s", raw)
	}
	return s
}

// encodeFromInput builds the typed value from the golden `input` and returns its
// borsh encoding.
func encodeFromInput(t *testing.T, v borshVector) []byte {
	t.Helper()
	e := NewEncoder()
	switch v.Type {
	case "u8":
		n, _ := strconv.ParseUint(jsonStr(t, v.Input), 10, 8)
		e.U8(uint8(n))
	case "u16":
		n, _ := strconv.ParseUint(jsonStr(t, v.Input), 10, 16)
		e.U16(uint16(n))
	case "u32":
		n, _ := strconv.ParseUint(jsonStr(t, v.Input), 10, 32)
		e.U32(uint32(n))
	case "u64":
		n, _ := strconv.ParseUint(jsonStr(t, v.Input), 10, 64)
		e.U64(n)
	case "u128":
		u, err := U128FromString(jsonStr(t, v.Input))
		if err != nil {
			t.Fatalf("%s: %v", v.Name, err)
		}
		e.U128(u)
	case "i8":
		n, _ := strconv.ParseInt(jsonStr(t, v.Input), 10, 8)
		e.I8(int8(n))
	case "i16":
		n, _ := strconv.ParseInt(jsonStr(t, v.Input), 10, 16)
		e.I16(int16(n))
	case "i32":
		n, _ := strconv.ParseInt(jsonStr(t, v.Input), 10, 32)
		e.I32(int32(n))
	case "i64":
		n, _ := strconv.ParseInt(jsonStr(t, v.Input), 10, 64)
		e.I64(n)
	case "i128":
		i, err := I128FromString(jsonStr(t, v.Input))
		if err != nil {
			t.Fatalf("%s: %v", v.Name, err)
		}
		e.I128(i)
	case "bool":
		var b bool
		if err := json.Unmarshal(v.Input, &b); err != nil {
			t.Fatalf("%s: bool input: %v", v.Name, err)
		}
		e.Bool(b)
	case "address":
		b, _ := hex.DecodeString(jsonStr(t, v.Input))
		e.Address(AddressFromBytes(b))
	case "hash32":
		b, _ := hex.DecodeString(jsonStr(t, v.Input))
		e.Bytes32(Bytes32FromBytes(b))
	case "bytes":
		b, _ := hex.DecodeString(jsonStr(t, v.Input))
		e.Bytes(b)
	case "string":
		e.String(jsonStr(t, v.Input))
	case "vec_u64":
		var items []string
		if err := json.Unmarshal(v.Input, &items); err != nil {
			t.Fatalf("%s: vec input: %v", v.Name, err)
		}
		vs := make([]uint64, len(items))
		for i, s := range items {
			vs[i], _ = strconv.ParseUint(s, 10, 64)
		}
		e.VecU64(vs)
	default:
		t.Fatalf("%s: unknown type %q", v.Name, v.Type)
	}
	return e.Finish()
}

// reencodeGolden decodes the golden bytes and re-encodes them; returns the
// re-encoding and the number of undecoded bytes left (must be 0).
func reencodeGolden(t *testing.T, typ string, golden []byte) ([]byte, int) {
	t.Helper()
	d := NewDecoder(golden)
	e := NewEncoder()
	switch typ {
	case "u8":
		e.U8(d.U8())
	case "u16":
		e.U16(d.U16())
	case "u32":
		e.U32(d.U32())
	case "u64":
		e.U64(d.U64())
	case "u128":
		e.U128(d.U128())
	case "i8":
		e.I8(d.I8())
	case "i16":
		e.I16(d.I16())
	case "i32":
		e.I32(d.I32())
	case "i64":
		e.I64(d.I64())
	case "i128":
		e.I128(d.I128())
	case "bool":
		e.Bool(d.Bool())
	case "address":
		e.Address(d.Address())
	case "hash32":
		e.Bytes32(d.Bytes32())
	case "bytes":
		e.Bytes(d.Bytes())
	case "string":
		e.String(d.String())
	case "vec_u64":
		e.VecU64(d.VecU64())
	default:
		t.Fatalf("unknown type %q", typ)
	}
	return e.Finish(), d.Remaining()
}

func TestBorshGoldenParity(t *testing.T) {
	vecs := loadBorshGoldens(t)
	t.Logf("replaying %d golden vectors × 2 directions", len(vecs))
	for _, v := range vecs {
		v := v
		t.Run(v.Name, func(t *testing.T) {
			// ENCODE
			got := hex.EncodeToString(encodeFromInput(t, v))
			if got != v.Borsh {
				t.Fatalf("encode mismatch\n type: %s\n want: %s\n got:  %s", v.Type, v.Borsh, got)
			}
			// REENCODE (decode → re-encode)
			golden, err := hex.DecodeString(v.Borsh)
			if err != nil {
				t.Fatalf("bad golden hex: %v", err)
			}
			re, rem := reencodeGolden(t, v.Type, golden)
			if rem != 0 {
				t.Fatalf("decode left %d unconsumed bytes", rem)
			}
			if reHex := hex.EncodeToString(re); reHex != v.Borsh {
				t.Fatalf("reencode mismatch\n want: %s\n got:  %s", v.Borsh, reHex)
			}
		})
	}
}
