#!/usr/bin/env python3
"""Emit c/tests/vectors_gen.h from vectors/child_address.json.

Decodes the golden child-address vectors into a static C
array so c/tests/child_test.c can recompute every preimage without a
JSON parser. Deterministic: vector order preserved, fixed formatting,
no timestamps. stdlib only.

Usage: python3 scripts/gen_c_vectors.py
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VECTORS = ROOT / "vectors" / "child_address.json"
OUT = ROOT / "c" / "tests" / "vectors_gen.h"

PREIMAGE_LEN = 107
PAIR_SORTED_MAX = 64


def fail(msg: str) -> None:
    print(f"gen_c_vectors: {msg}", file=sys.stderr)
    sys.exit(1)


def c_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def c_bytes(data: bytes, indent: str = "            ") -> str:
    """Fixed 12-bytes-per-line initializer; '{ 0 }' for empty."""
    if not data:
        return "{ 0 }"
    lines = []
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 12])
        lines.append(f"{indent}{chunk},")
    return "{\n" + "\n".join(lines) + "\n        }"


def decode_hex(v: dict, field: str, expect_len: int) -> bytes:
    raw = v.get(field)
    if raw is None:
        fail(f"vector {v.get('name', '?')!r}: missing {field}")
    try:
        data = bytes.fromhex(raw)
    except ValueError:
        fail(f"vector {v['name']!r}: {field} is not hex")
    if len(data) != expect_len:
        fail(f"vector {v['name']!r}: {field} is {len(data)} bytes, want {expect_len}")
    return data


def main() -> None:
    doc = json.loads(VECTORS.read_text())
    vectors = doc.get("vectors")
    if not vectors:
        fail(f"no vectors in {VECTORS}")

    entries = []
    for v in vectors:
        name = v["name"]
        parent = decode_hex(v, "parent", 32)
        template = decode_hex(v, "template", 32)
        salt = decode_hex(v, "salt", 32)
        preimage = decode_hex(v, "preimage", PREIMAGE_LEN)

        pair_args = v.get("salt_source_pair_args")
        if pair_args is not None:
            if len(pair_args) != 2:
                fail(f"vector {name!r}: salt_source_pair_args wants 2 entries")
            pair_a, pair_b = (bytes.fromhex(h) for h in pair_args)
            if len(pair_a) != 32 or len(pair_b) != 32:
                fail(f"vector {name!r}: pair args must be 32 bytes each")
            pair_sorted = decode_hex(v, "salt_source_borsh", PAIR_SORTED_MAX)
        else:
            pair_a = pair_b = pair_sorted = b""

        entries.append(
            "    {\n"
            f"        {c_string(name)},\n"
            f"        /* parent */ {c_bytes(parent)},\n"
            f"        /* template_addr */ {c_bytes(template)},\n"
            f"        /* salt */ {c_bytes(salt)},\n"
            f"        /* preimage */ {c_bytes(preimage)},\n"
            f"        /* has_pair_args */ {1 if pair_args is not None else 0},\n"
            f"        /* pair_a */ {c_bytes(pair_a)},\n"
            f"        /* pair_b */ {c_bytes(pair_b)},\n"
            f"        /* pair_sorted_len */ {len(pair_sorted)},\n"
            f"        /* pair_sorted */ {c_bytes(pair_sorted)},\n"
            "    },"
        )

    body = "\n".join(entries)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "/* generated by scripts/gen_c_vectors.py from"
        " vectors/child_address.json — do not edit; regenerate after"
        " vector changes */\n"
        "\n"
        "#ifndef PYDE_TESTS_VECTORS_GEN_H\n"
        "#define PYDE_TESTS_VECTORS_GEN_H\n"
        "\n"
        "#include <stdint.h>\n"
        "\n"
        "typedef struct {\n"
        "    const char* name;\n"
        "    uint8_t parent[32];\n"
        "    uint8_t template_addr[32];\n"
        "    uint8_t salt[32];\n"
        f"    uint8_t preimage[{PREIMAGE_LEN}];\n"
        "    int has_pair_args;       /* 1 when salt_source_pair_args present */\n"
        "    uint8_t pair_a[32];      /* args as recorded — deliberately unsorted */\n"
        "    uint8_t pair_b[32];\n"
        "    int pair_sorted_len;     /* 64 when has_pair_args, else 0 */\n"
        f"    uint8_t pair_sorted[{PAIR_SORTED_MAX}];  /* the vector's salt_source_borsh */\n"
        "} pyde_child_vector;\n"
        "\n"
        "static const pyde_child_vector PYDE_CHILD_VECTORS[] = {\n"
        f"{body}\n"
        "};\n"
        "\n"
        "#define PYDE_CHILD_VECTOR_COUNT \\\n"
        "    (sizeof(PYDE_CHILD_VECTORS) / sizeof(PYDE_CHILD_VECTORS[0]))\n"
        "\n"
        "#endif /* PYDE_TESTS_VECTORS_GEN_H */\n"
    )
    print(f"gen_c_vectors: wrote {OUT.relative_to(ROOT)} ({len(vectors)} vectors)")


if __name__ == "__main__":
    main()
